# Generated by Django 4.0.3 on 2022-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('curso', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('observaciones', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('profesor', models.CharField(max_length=40)),
                ('dias', models.CharField(max_length=40)),
                ('horario', models.IntegerField()),
                ('observaciones', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('curso', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('observaciones', models.CharField(max_length=1500)),
            ],
        ),
    ]
