# Generated by Django 4.0.3 on 2022-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitmoUrbano', '0002_alumno_imagen_curso_imagen_profesor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/alumnos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/profesores'),
        ),
    ]
