# Generated by Django 4.0.3 on 2022-06-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitmoUrbano', '0007_contacto_alter_curso_imagen_alter_profesor_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='clase',
        ),
    ]
